# Generated by Django 5.2.13 on 2026-04-15 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "gender",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女")],
                        max_length=4,
                        verbose_name="性别",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="身高(cm)",
                    ),
                ),
                ("diagnosis_year", models.IntegerField(verbose_name="确诊年份")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="在管状态"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建档时间"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="doctors.doctor",
                        verbose_name="责任医生",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "患者",
                "verbose_name_plural": "患者",
            },
        ),
        migrations.CreateModel(
            name="MedicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField(verbose_name="计划服药时间")),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际打卡时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("taken", "已服药"),
                            ("missed", "漏服"),
                            ("skipped", "跳过"),
                        ],
                        max_length=10,
                        verbose_name="打卡状态",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="doctors.medicationplan",
                        verbose_name="所属方案",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_records",
                        to="patients.patient",
                        verbose_name="所属患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "用药打卡记录",
                "verbose_name_plural": "用药打卡记录",
                "ordering": ["-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fasting_glucose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="空腹血糖(mmol/L)",
                    ),
                ),
                (
                    "postmeal_glucose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="餐后2h血糖(mmol/L)",
                    ),
                ),
                (
                    "systolic_bp",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="收缩压(mmHg)"
                    ),
                ),
                (
                    "diastolic_bp",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="舒张压(mmHg)"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="体重(kg)",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[("voice", "语音录入"), ("text", "文字录入")],
                        max_length=10,
                        verbose_name="录入方式",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="录入时间"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="patients.patient",
                        verbose_name="所属患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康记录",
                "verbose_name_plural": "健康记录",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
