# Generated by Django 5.2.13 on 2026-04-15 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("green", "绿码（正常）"),
                            ("yellow", "黄码（警示）"),
                            ("red", "红码（危险）"),
                        ],
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="加权评分"
                    ),
                ),
                (
                    "trigger_indicators",
                    models.JSONField(blank=True, null=True, verbose_name="异常指标"),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评估时间"),
                ),
                (
                    "health_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_record",
                        to="patients.healthrecord",
                        verbose_name="关联健康记录",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_records",
                        to="patients.patient",
                        verbose_name="所属患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "风险评估记录",
                "verbose_name_plural": "风险评估记录",
                "ordering": ["-evaluated_at"],
            },
        ),
    ]
