# Generated by Django 5.2.13 on 2026-04-15 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drug_name",
                    models.CharField(max_length=100, verbose_name="药品名称"),
                ),
                ("dosage", models.CharField(max_length=50, verbose_name="剂量")),
                (
                    "frequency",
                    models.CharField(max_length=20, verbose_name="每日服药频次"),
                ),
                (
                    "remind_times",
                    models.CharField(
                        help_text="逗号分隔，如 08:00,20:00",
                        max_length=100,
                        verbose_name="提醒时间",
                    ),
                ),
                ("total_days", models.IntegerField(verbose_name="处方总天数")),
                ("start_date", models.DateField(verbose_name="方案起始日期")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否生效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用药方案",
                "verbose_name_plural": "用药方案",
            },
        ),
        migrations.CreateModel(
            name="VisitTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("online", "线上轻问诊"),
                            ("offline", "线下门诊"),
                            ("home", "上门巡诊"),
                        ],
                        max_length=20,
                        verbose_name="随访方式",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "普通"), ("urgent", "紧急")],
                        default="normal",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="截止日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("completed", "已完成"),
                            ("deferred", "已延期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="随访备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "随访任务",
                "verbose_name_plural": "随访任务",
                "ordering": ["-priority", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "医生",
                "verbose_name_plural": "医生",
            },
        ),
    ]
