# Generated by Django 5.2.13 on 2026-04-15 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicationplan",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medication_plans",
                to="patients.patient",
                verbose_name="所属患者",
            ),
        ),
        migrations.AddField(
            model_name="visittask",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_tasks",
                to="doctors.doctor",
                verbose_name="负责医生",
            ),
        ),
        migrations.AddField(
            model_name="visittask",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_tasks",
                to="patients.patient",
                verbose_name="所属患者",
            ),
        ),
    ]
